# Server configuration
server:
  port: 9191
  forward-headers-strategy: framework
  shutdown: graceful

# Spring configuration
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m # The server will wait up to one minute for active requests to complete
  application:
    name: gateway-service # The server application name
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      #      httpclient:
      #        ssl:
      #          use-insecure-trust-manager: true
      discovery:
        locator:
          enabled: true
      # Routing Services

      # User Service
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        # Plant Service
        - id: plant-service
          uri: lb://PLANT-SERVICE
          predicates:
            - Path=/plant/**
          filters:
            - RewritePath=/plant/(?<path>.*), /$\{path}

        # General Service
        - id: general-service
          uri: lb://GENERAL-SERVICE
          predicates:
            - Path=/general/**
          filters:
            - RewritePath=/general/(?<path>.*), /$\{path}

        # MrpData Service
        - id: mrp-service
          uri: lb://MRP-SERVICE
          predicates:
            - Path=/mrp/**
          filters:
            - RewritePath=/mrp/(?<path>.*), /$\{path}

        # Sales Service
        - id: sales-service
          uri: lb://SALES-SERVICE
          predicates:
            - Path=/sales/**
          filters:
            - RewritePath=/sales/(?<path>.*), /$\{path}

        # Vendor Service
        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/vendor/**
          filters:
            - RewritePath=/vendor/(?<path>.*), /$\{path}

          # Setting Service
        - id: setting-service
          uri: lb://SETTING-SERVICE
          predicates:
            - Path=/setting/**
          filters:
            - RewritePath=/setting/(?<path>.*), /$\{path}

        # Value Service
        - id: value-service
          uri: lb://VALUE-SERVICE
          predicates:
            - Path=/value/**
          filters:
            - RewritePath=/value/(?<path>.*), /$\{path}

        # Attribute Service
        - id: attribute-service
          uri: lb://ATTRIBUTE-SERVICE
          predicates:
            - Path=/attribute/**
          filters:
            - RewritePath=/attribute/(?<path>.*), /$\{path}

        # Dictionary Service
        - id: dictionary-service
          uri: lb://DICTIONARY-SERVICE
          predicates:
            - Path=/dictionary/**
          filters:
            - RewritePath=/dictionary/(?<path>.*), /$\{path}

        # Request Item Service
        - id: request-service
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/request/**
          filters:
            - RewritePath=/request/(?<path>.*), /$\{path}

        # Dynamic Service
        - id: dynamic-service
          uri: lb://DYNAMIC-SERVICE
          predicates:
            - Path=/dynamic/**
          filters:
            - RewritePath=/dynamic/(?<path>.*), /$\{path}

        # Common OpenApi
        - id: openapi
#          uri: http://${server.address}:${server.port}
          uri: lb://GATEWAY-SERVICE
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

#
#        - id: EUREKA-SERVER
#          uri: http://localhost:8761
#          predicates:
#            - Path=/**

# Eureka Server configuration
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# Actuator endpoints configuration
management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: "*"

  # Zipkin configuration
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

# OpenApi Swagger configuration
springdoc:
  service:
    title: Gateway-Service doc
    version: 1.0.1
  api-docs:
    groups:
      enabled: true
    enabled: true
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    tags-sorter: method
    try-it-out-enabled: true
    deep-linking: true
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    display-operation-id: false
    filter: false
    show-extensions: false
    use-root-path: true
    urls:
      - name: gateway-service
        url: /v3/api-docs
        display-name: Gateway

      - name: user-service
        url: /v3/api-docs/user
        display-name: User

      - name: plant-service
        url: /v3/api-docs/plant
        display-name: Plant

      - name: general-service
        url: /v3/api-docs/general
        display-name: General

      - name: mrp-service
        url: /v3/api-docs/mrp
        display-name: Mrp Data

      - name: sales-service
        url: /v3/api-docs/sales
        display-name: Sales

      - name: vendor-service
        url: /v3/api-docs/vendor
        display-name: Vendor

      - name: setting-service
        url: /v3/api-docs/setting
        display-name: Setting

      - name: value-service
        url: /v3/api-docs/value
        display-name: Value

      - name: attribute-service
        url: /v3/api-docs/attribute
        display-name: Attribute

      - name: dictionary-service
        url: /v3/api-docs/dictionary
        display-name: Create Template

      - name: request-service
        url: /v3/api-docs/request
        display-name: Request Item

      - name: dynamic-service
        url: /v3/api-docs/dynamic
        display-name: Dynamic

  cache:
    disabled: false
  show-actuator: true
  writer-with-default-pretty-printer: true

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: TRACE

logging:
  level:
    root: info
    "[org.springframework.cloud.gateway.route.RouteDefinitionLocator]": info
    "[org.springframework.cloud.gateway]": trace
    "[org.springframework.security]": debug
