# Server configuration
server:
  port: 9191
  forward-headers-strategy: framework
  shutdown: graceful

# Spring configuration
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m # The server will wait up to one minute for active requests to complete
  application:
    name: GATEWAY-SERVICE # The server application name
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        CorsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      # Routing Services

      # User Service
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        # Plant Service
        - id: PLANT-SERVICE
          uri: lb://PLANT-SERVICE
          predicates:
            - Path=/plant/**
          filters:
            - RewritePath=/plant/(?<path>.*), /$\{path}

        # General Service
        - id: GENERAL-SERVICE
          uri: lb://GENERAL-SERVICE
          predicates:
            - Path=/general/**
          filters:
            - RewritePath=/general/(?<path>.*), /$\{path}

        # MrpData Service
        - id: MRP-SERVICE
          uri: lb://MRP-SERVICE
          predicates:
            - Path=/mrp/**
          filters:
            - RewritePath=/mrp/(?<path>.*), /$\{path}

        # Sales Service
        - id: SALES-SERVICE
          uri: lb://SALES-SERVICE
          predicates:
            - Path=/sales/**
          filters:
            - RewritePath=/sales/(?<path>.*), /$\{path}

        # Vendor Service
        - id: VENDOR-SERVICE
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/vendor/**
          filters:
            - RewritePath=/vendor/(?<path>.*), /$\{path}

          # Setting Service
        - id: SETTING-SERVICE
          uri: lb://SETTING-SERVICE
          predicates:
            - Path=/setting/**
          filters:
            - RewritePath=/setting/(?<path>.*), /$\{path}

        # Common OpenApi
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

#
#        - id: EUREKA-SERVER
#          uri: http://localhost:8761
#          predicates:
#            - Path=/**

# Eureka Server configuration
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# Actuator endpoints configuration
management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: "*"

# OpenApi Swagger configuration
springdoc:
  service:
    title: Gateway-Service doc
    version: 1.0.1
  api-docs:
    groups:
      enabled: true
    enabled: true
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    tags-sorter: method
    try-it-out-enabled: true
    deep-linking: true
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    display-operation-id: false
    filter: false
    show-extensions: false
    urls:
      - name: GATEWAY-SERVICE
        url: /v3/api-docs
        display-name: Gateway

      - name: USER-SERVICE
        url: /v3/api-docs/user
        display-name: User

      - name: PLANT-SERVICE
        url: /v3/api-docs/plant
        display-name: Plant

      - name: GENERAL-SERVICE
        url: /v3/api-docs/general
        display-name: General

      - name: MRP-SERVICE
        url: /v3/api-docs/mrp
        display-name: Mrp Data

      - name: SALES-SERVICE
        url: /v3/api-docs/sales
        display-name: Sales

      - name: VENDOR-SERVICE
        url: /v3/api-docs/vendor
        display-name: Vendor

      - name: SETTING-SERVICE
        url: /v3/api-docs/setting
        display-name: General Setting

    use-root-path: true

  cache:
    disabled: false
  show-actuator: false
  writer-with-default-pretty-printer: true

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: TRACE

logging:
  level:
    org.springframework.security: DEBUG
