# Server configuration
server:
  port: 8011
  forward-headers-strategy: framework
  shutdown: graceful


# Spring configuration
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m  # The server will wait up to one minute for active requests to complete
  application:
    name: DICTIONARY-SERVICE   # The server application name

  # Db Configuration
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/Prosol
    password: imu123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

# Eureka Server configuration
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# Actuator endpoints configuration
management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: "*"

  # Zipkin configuration
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0


# OpenApi Swagger configuration
springdoc:
  service:
    title: Dictionary-Service doc
    version: 1.0.1
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    tags-sorter: method
    try-it-out-enabled: true
    deep-linking: true
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    display-operation-id: false
    filter: false
    show-extensions: false
  cache:
    disabled: off
  show-actuator: false
  writer-with-default-pretty-printer: true
